branch-defaults:
  master:
    environment: atvalidation-prod
    group_suffix: null
global:
  application_name: atvalidation
  default_ec2_keyname: autotaskvalidation
  default_platform: Python 3.4
  default_region: eu-west-1
  profile: eb-cli
  sc: git
